# Reduce Data to parquet

**Note: Run only once**
- select a subset of columns
- save in parquet format

In [ ]:
# change the filepath as required, we have selected the folder with the latest date

## ------ California -------

# filepath = '../data/VM2--CA--2022-04-25/'
# DEMO_filename_in = 'VM2--CA--2022-04-25-DEMOGRAPHIC.tab'
# VOTE_filename_in = 'VM2--CA--2022-04-25-VOTEHISTORY.tab'
# DEMO_filename_out = 'VM2--CA--2022-04-25-DEMOGRAPHIC_selected_cols.parquet'
# VOTE_filename_out = 'VM2--CA--2022-04-25-VOTEHISTORY_selected_cols.parquet'

## ------ Colorado -------

# filepath = '../data/VM2--CO--2022-04-26/'
# DEMO_filename_in = 'VM2--CO--2022-04-26-DEMOGRAPHIC.tab'
# VOTE_filename_in = 'VM2--CO--2022-04-26-VOTEHISTORY.tab'
# DEMO_filename_out = 'VM2--CO--2022-04-26-DEMOGRAPHIC_selected_cols.parquet'
# VOTE_filename_out = 'VM2--CO--2022-04-26-VOTEHISTORY_selected_cols.parquet'


# # ------ Maryland -------

# filepath = '../data/VM2--MD--2022-04-08/'
# DEMO_filename_in = 'VM2--MD--2022-04-08-DEMOGRAPHIC.tab'
# VOTE_filename_in = 'VM2--MD--2022-04-08-VOTEHISTORY.tab'
# DEMO_filename_out = 'VM2--MD--2022-04-08-DEMOGRAPHIC_selected_cols.parquet'
# VOTE_filename_out = 'VM2--MD--2022-04-08-VOTEHISTORY_selected_cols.parquet'


# # ------ Maine -------

# filepath = '../data/VM2--ME--2022-03-02/'
# DEMO_filename_in = 'VM2--ME--2022-03-02-DEMOGRAPHIC.tab'
# VOTE_filename_in = 'VM2--ME--2022-03-02-VOTEHISTORY.tab'
# DEMO_filename_out = 'VM2--ME--2022-03-02-DEMOGRAPHIC_selected_cols.parquet'
# VOTE_filename_out = 'VM2--ME--2022-03-02-VOTEHISTORY_selected_cols.parquet'


# # ------ Minnesota -------

# filepath = '../data/VM2--MN--2022-03-25/'
# DEMO_filename_in = 'VM2--MN--2022-03-25-DEMOGRAPHIC.tab'
# VOTE_filename_in = 'VM2--MN--2022-03-25-VOTEHISTORY.tab'
# DEMO_filename_out = 'VM2--MN--2022-03-25-DEMOGRAPHIC_selected_cols.parquet'
# VOTE_filename_out = 'VM2--MN--2022-03-25-VOTEHISTORY_selected_cols.parquet'


# # ------ New Mexico -------

# filepath = '../data/VM2--NM--2022-03-30/'
# DEMO_filename_in = 'VM2--NM--2022-03-30-DEMOGRAPHIC.tab'
# VOTE_filename_in = 'VM2--NM--2022-03-30-VOTEHISTORY.tab'
# DEMO_filename_out = 'VM2--NM--2022-03-30-DEMOGRAPHIC_selected_cols.parquet'
# VOTE_filename_out = 'VM2--NM--2022-03-30-VOTEHISTORY_selected_cols.parquet'


# # ------ Vermont -------

# filepath = '../data/VM2--VT--2022-04-20/'
# DEMO_filename_in = 'VM2--VT--2022-04-20-DEMOGRAPHIC.tab'
# VOTE_filename_in = 'VM2--VT--2022-04-20-VOTEHISTORY.tab'
# DEMO_filename_out = 'VM2--VT--2022-04-20-DEMOGRAPHIC_selected_cols.parquet'
# VOTE_filename_out = 'VM2--VT--2022-04-20-VOTEHISTORY_selected_cols.parquet'


# # ------ Utah -------

# filepath = '../data/VM2--UT--2022-03-30/'
# DEMO_filename_in = 'VM2--UT--2022-03-30-DEMOGRAPHIC.tab'
# VOTE_filename_in = 'VM2--UT--2022-03-30-VOTEHISTORY.tab'
# DEMO_filename_out = 'VM2--UT--2022-03-30-DEMOGRAPHIC_selected_cols.parquet'
# VOTE_filename_out = 'VM2--UT--2022-03-30-VOTEHISTORY_selected_cols.parquet'

# 1. Reduce DEMOGRAPHIC file to parquet

**Note: Run only once**
- select a subset of demography columns
- save in parquet format

In [ ]:
selected_variables = ['LALVOTERID',
                      'Residence_Addresses_City', 
                      'County',
                      'EthnicGroups_EthnicGroup1Desc',
                      'Voters_OfficialRegDate', 
                      'Voters_Age',
                      'Voters_Gender',        
                      'CommercialData_Education',
                      'CommercialData_EstimatedHHIncomeAmount',
                      'CommercialData_EstimatedHHIncome',
                      'FECDonors_NumberOfDonations',
                      'FECDonors_TotalDonationsAmount', 
                      'Parties_Description'
                     ]

state_demographic = pd.read_csv(f'{filepath}{DEMO_filename_in}', 
                                sep='\t', dtype=str, encoding='unicode_escape',
                                usecols=selected_variables)

state_demographic.head()

,LALVOTERID,Residence_Addresses_City,Voters_Gender,Voters_Age,Parties_Description,EthnicGroups_EthnicGroup1Desc,Voters_OfficialRegDate,County,CommercialData_Education,CommercialData_EstimatedHHIncome,CommercialData_EstimatedHHIncomeAmount,FECDonors_NumberOfDonations,FECDonors_TotalDonationsAmount
0,LALMN152549717,Palisade,M,52,Non-Partisan,European,11/03/2020,AITKIN,NaN,$54137,NaN,NaN,NaN
1,LALMN152603668,Hill City,F,81,Democratic,European,05/11/2001,AITKIN,Some College -Extremely Likely,$22000,NaN,NaN,NaN
2,LALMN152603669,Hill City,M,82,Democratic,European,09/10/2002,AITKIN,NaN,$22000,NaN,NaN,NaN
3,LALMN153373196,McGregor,M,54,Democratic,NaN,11/02/2004,AITKIN,Some College -Extremely Likely,$14000,NaN,NaN,NaN
4,LALMN152949755,Aitkin,M,64,Non-Partisan,European,11/04/2008,AITKIN,NaN,NaN,NaN,NaN,NaN

In [ ]:
state_demographic.to_parquet(f'{filepath}{DEMO_filename_out}')

# 2. Reduce VOTEHISTORY file to parquet

**Note: Run only once**
1. load the data with only one row to find out which dates are  "General" and "Local_Municipal" 
2. create a list of columns that contains those dates
3. reload the data with only those columns and the voter ID (`LALVOTERID`) and all rows
4. save the data in parquet format

In [ ]:
# 1. select only one rows to find the column names that are General and Local_or_Municipal elections
state_voterhistory_cols = pd.read_csv(f'{filepath}{VOTE_filename_in}',
                                 sep='\t', dtype=str, encoding='unicode_escape',
                                nrows=1)
                                
state_voterhistory_cols.head()

,LALVOTERID,Special_2022_02_08,Consolidated_General_2021_11_02,Consolidated_Primary_2021_08_10,Special_2021_05_11,Special_2021_04_13,Local_or_Municipal_2021_03_09,Special_2021_02_09,General_2020_11_03,Primary_2020_08_11,...,BallotReturnDate_General_2018_11_06,BallotReturnDate_Primary_2018_08_14,BallotReturnDate_General_2016_11_08,BallotReturnDate_Primary_2016_08_09,BallotReturnDate_General_2014_11_04,BallotReturnDate_Primary_2014_08_12,BallotReturnDate_General_2012_11_06,BallotReturnDate_Primary_2012_08_14,BallotReturnDate_General_2010_11_02,BallotReturnDate_Primary_2010_08_10
0,LALMN152549717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#2. select only voter ID and columns with General or Local_or_Municipal election dates

GE_cols = [col for col in state_voterhistory_cols.columns if col.startswith('General')]
print("total number of General election dates", len(GE_cols))

LM_cols = [col for col in state_voterhistory_cols.columns if col.startswith('Local_or_Municipal')]
print("total number of Local or Municipal election dates", len(LM_cols))

needed_variables = ['LALVOTERID'] + LM_cols + GE_cols

total number of General election dates 14
total number of Local or Municipal election dates 66

In [ ]:
#3. reload the data with all columns related to General or Local_or_Municipal election dates and all rows 
state_voterhistory = pd.read_csv(f'{filepath}{VOTE_filename_in}',
                                 sep='\t', dtype=str, encoding='unicode_escape',
                                 usecols=needed_variables)
                                
state_voterhistory.head(5)

,LALVOTERID,Local_or_Municipal_2021_03_09,General_2020_11_03,Local_or_Municipal_2020_03_10,Local_or_Municipal_2019_03_12,General_2018_11_06,Local_or_Municipal_2018_03_13,Local_or_Municipal_2017_03_14,General_2016_11_08,Local_or_Municipal_2016_03_08,...,Local_or_Municipal_2001_06_19,Local_or_Municipal_2001_06_05,Local_or_Municipal_2001_05_22,Local_or_Municipal_2001_03_13,General_2000_11_07,Local_or_Municipal_2000_11_07,Local_or_Municipal_2000_09_12,General_1998_11_03,General_1996_11_05,General_1994_11_08
0,LALMN152549717,NaN,Y,NaN,NaN,NaN,NaN,NaN,Y,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LALMN152603668,NaN,Y,NaN,NaN,Y,NaN,NaN,Y,NaN,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,Y,Y,Y
2,LALMN152603669,NaN,Y,NaN,NaN,Y,NaN,NaN,Y,NaN,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,Y,Y,Y
3,LALMN153373196,NaN,Y,NaN,NaN,NaN,NaN,NaN,Y,NaN,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,Y
4,LALMN152949755,NaN,Y,NaN,NaN,Y,NaN,NaN,Y,NaN,...,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,Y,NaN

In [ ]:
#4. save to parquet format
state_voterhistory.to_parquet(f'{filepath}{VOTE_filename_out}')